[package]
name = "hello_lib"
version = "0.1.0"
authors = ["bsechter"]
edition = "2018"

[lib]
name = "hello"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
